export const Municipalities = [
  "Ada",
  "Aleksandrovac",
  "Aleksinac",
  "Alibunar",
  "Apatin",
  "Aranđelovac",
  "Arilje",
  "Babušnica",
  "Bajina Bašta",
  "Barajevo",
  "Batočina",
  "Bač",
  "Bačka Palanka",
  "Bačka Topola",
  "Bački Petrovac",
  "Bela Crkva",
  "Bela Palanka",
  "Beočin",
  "Bečej",
  "Blace",
  "Bogatić",
  "Bojnik",
  "Boljevac",
  "Bor",
  "Bosilegrad",
  "Brus",
  "Bujanovac",
  "Crna Trava",
  "Crveni Krst",
  "Despotovac",
  "Dečani",
  "Dimitrovgrad",
  "Doljevac",
  "Gadžin Han",
  "Glogovac",
  "Gnjilane",
  "Golubac",
  "Gora",
  "Gornji Milanovac",
  "Grocka",
  "inđija",
  "Irig",
  "Istok",
  "Ivanjica",
  "Jagodina",
  "Kanjiža",
  "Kačanik",
  "Kikinda",
  "Kladovo",
  "Klina",
  "Knić",
  "Knjaževac",
  "Koceljeva",
  "Kosjerić",
  "Kosovo Polje",
  "Kosovska Kamenica",
  "Kosovska Mitrovica",
  "Kostolac",
  "Kovačica",
  "Kovin",
  "Kragujevac",
  "Kraljevo",
  "Krupanj",
  "Kruševac",
  "Kula",
  "Kuršumlija",
  "Kučevo",
  "Lajkovac",
  "Lapovo",
  "Lazarevac",
  "Lebane",
  "Leposavić",
  "Leskovac",
  "Lipljan",
  "Ljig",
  "Ljubovija",
  "Loznica",
  "Lučani",
  "Majdanpek",
  "Mali Iđoš",
  "Mali Zvornik",
  "Malo Crniće",
  "Medijana",
  "Medveđa",
  "Merošina",
  "Mionica",
  "Mladenovac",
  "Negotin",
  "Niška Banja",
  "Nova Crnja",
  "Nova Varoš",
  "Novi Beograd",
  "Novi Bečej",
  "Novi Kneževac",
  "Novi Pazar",
  "Novi Sad",
  "Novo Brdo",
  "Obilić",
  "Obrenovac",
  "Odžaci",
  "Opovo",
  "Orahovac",
  "Osečina",
  "Palilula (Niš)",
  "Palilula (Beograd)",
  "Pantelej",
  "Pančevo",
  "Paraćin",
  "Petrovac na Mlavi",
  "Peć",
  "Pećinci",
  "Pirot",
  "Plandište",
  "Podujevo",
  "Požarevac",
  "Požega",
  "Preševo",
  "Priboj",
  "Prijepolje",
  "Prizren",
  "Priština",
  "Prokuplje",
  "Rakovica",
  "Rača",
  "Raška",
  "Ražanj",
  "Rekovac",
  "Ruma",
  "Savski Venac",
  "Senta",
  "Sevojno",
  "Sečanj",
  "Sjenica",
  "Smederevo",
  "Smederevska Palanka",
  "Sokobanja",
  "Sombor",
  "Sopot",
  "Srbica",
  "Srbobran",
  "Sremska Mitrovica",
  "Sremski Karlovci",
  "Stara Pazova",
  "Stari Grad",
  "Subotica",
  "Surdulica",
  "Surčin",
  "Suva Reka",
  "Svilajnac",
  "Svrljig",
  "Temerin",
  "Titel",
  "Topola",
  "Trgovište",
  "Trstenik",
  "Tutin",
  "Ub",
  "Uroševac",
  "Užice",
  "Valjevo",
  "Varvarin",
  "Velika Plana",
  "Veliko Gradište",
  "Vitina",
  "Vladimirci",
  "Vladičin Han",
  "Vlasotince",
  "Voždovac",
  "Vranje",
  "Vranjska Banja",
  "Vračar",
  "Vrbas",
  "Vrnjačka Banja",
  "Vršac",
  "Vučitrn",
  "Zaječar",
  "Zemun",
  "Zrenjanin",
  "Zubin Potok",
  "Zvezdara",
  "Zvečan",
  "Ćićevac",
  "Ćuprija",
  "Čajetina",
  "Čačak",
  "Čoka",
  "Čukarica",
  "Đakovica",
  "Šabac",
  "Šid",
  "Štimlje",
  "Štrpce",
  "Žabalj",
  "Žabari",
  "Žagubica",
  "Žitište",
  "Žitorađa",
];
